networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1024 # The user ID of the current user
      - PGID=100 # The group ID of the current user
      - TZ=Europe/London # The Timezone where you live
      - MYSQL_ROOT_PASSWORD=CHANGE_THIS_PASSWORD # Change this password
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=CHANGE_THIS_PASSWORD2 # Change this password
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - "./mariadb:/config"
    networks:
      private_network:
        ipv4_address: 10.2.0.5

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    depends_on: [mariadb]
    restart: unless-stopped
    dns:
      - 10.2.0.100 # Connects through Pi-Hole mainly to gain internet access for apps. Could change to 1.1.1.1 for Cloudflare DNS
    ports: # Could include port 4433:443 for HTTPS
      - 8080:80
    links:
      - mariadb
    volumes:
      - "./nextcloud/www/html/config:/var/www/html/config" # This is for editing trusted domains
    networks:
      private_network:
        ipv4_address: 10.2.0.4 # Your NextCloud instance would be located here after connected to WireGuard

  wg-easy:
    depends_on: [pihole]
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=YOUR_PUBLIC_IP # Change this to your public IP
      - WG_PORT=51820
      - WG_DEFAULT_DNS=10.2.0.100,10.2.0.100 # The DNS 10.2.0.100 to connect with Pi-Hole
      - PASSWORD=CHANGE_THIS_PASSWORD # Change this password to access the web UI
    restart: unless-stopped
    ports:
      - "51820:51820/udp" # This port 51820 is for the actual VPN, port forward this to access it outside your network
      - "51821:51821/tcp" # This port 51821 is for the web UI
    volumes:
      - "./etc-wireguard/:/etc/wireguard"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1  
    environment:
      - TZ=Europe/London
      - WEBPASSWORD= # Blank password - Can be whatever you want.
      - ServerIP=10.2.0.100 # Internal IP of pihole
    volumes: # Volumes store your data between container upgrades
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    ports:
      - "5353:53/tcp" # This should be for the DNS stuff
      - "8081:80/tcp" # This is for accessing your Pi-Hole admin server (10.2.0.100/admin)
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.100
